data = {
    "TOKEN": "MTEyNDI5NDQwMTM2NDA3NDU0OA.G97hI6.qK2UEFrSypF1h2ZFUrCGe2X5-xz9rwgP_QHNWA",
    
    
    "cry": ["https://media.tenor.com/tK-bs8K6ZQIAAAAd/remi-horimiya.gif" , "https://media.tenor.com/sKvXD9IUYT8AAAAM/anime-animu.gif" , "https://media.tenor.com/A0g9Rrx4aNsAAAAC/sad-angry.gif" , "https://media.tenor.com/9gfJKZaNYMUAAAAC/anime-anime-cry.gif" , "https://media.tenor.com/j-mVhVzhSAYAAAAC/anime-cry.gif" , "https://media.tenor.com/tgVGh4R71MEAAAAC/anime-cry.gif" , "https://media.tenor.com/LompdqfJLYYAAAAC/sad-anime.gif"],
    "kiss": ["https://media.tenor.com/jnndDmOm5wMAAAAC/kiss.gif" , "https://media.tenor.com/Ogthkl9rYBMAAAAC/ichigo-hiro.gif" , "https://media.tenor.com/-_NJcR60b7UAAAAC/anime.gif" , "https://media.tenor.com/Bw0OLA1NefUAAAAC/anime-chuunibyou.gif" , "https://media.tenor.com/fVMPQro2eZAAAAAC/anime-kiss.gif" , "https://media.tenor.com/8mUI_rkXUuAAAAAC/kiss.gif" , "https://media.tenor.com/6J-id2YS8-MAAAAC/ichigo-kiss.gif" , "https://media.tenor.com/0mdCwkmGD1oAAAAC/kiss-love.gif"],
    "laughter": ["https://media.tenor.com/74Win7VdWDoAAAAC/anime-laughing.gif" , "https://media.tenor.com/xKvdQnAP8nwAAAAC/anime-laughing.gif" , "https://media.tenor.com/UioO8Xu5G3IAAAAC/anime-funny.gif" , "https://media.tenor.com/BP9vMzwRSZwAAAAC/laughing-lol.gif" , "https://media.tenor.com/m3eR2kqrb1oAAAAC/laugh.gif" , "https://media.tenor.com/KtmQpdErjCYAAAAC/junko-enoshima-laugh.gif"],
    "food": ["https://media.tenor.com/u5twDuNeGZwAAAAS/mukbang-food.gif" , "https://media.tenor.com/C-YaBCe1Z6wAAAAS/mukbang-food.gif" , "https://media.tenor.com/CjeRrs9XXnQAAAAM/mukbang-food.gif" , "https://media.tenor.com/YNishTVWjJkAAAAM/karnataka-food-karnataka.gif" , "https://media.tenor.com/jEUJUu9eO0gAAAAM/mukbang-food.gif" , "https://media.tenor.com/lY3aLLSQrtwAAAAM/mukbang-food.gif" , "https://media.tenor.com/5tVHmMSx050AAAAM/mukbang-food.gif" , "https://media.tenor.com/PqhHozGQsIUAAAAM/sauces-spices.gif" , "https://media.tenor.com/uO3Nlk3HWdYAAAAM/mukbang-food.gif" , "https://media.tenor.com/L8rnJ8zpkdEAAAAM/mukbang-food.gif" , "https://media.tenor.com/Re9AXev1g5UAAAAM/mukbang-food.gif"],
    "cats": ["https://media.tenor.com/J3XKVY7E-SoAAAAS/cats-cute-cats.gif" , "https://media.tenor.com/l37il_hI3tEAAAAM/smilecat.gif" , "https://media.tenor.com/LqWwwmMMuRsAAAAM/cat.gif" , "https://media.tenor.com/6pFkg0D_3W0AAAAM/cat-couple-cute-cats.gif" , "https://media.tenor.com/Ox1McvWB6dUAAAAM/cat-cats.gif" , "https://media.tenor.com/f_saBHiUTz0AAAAM/cute-cat.gif" , "https://media.tenor.com/zrpyKEyxZGwAAAAM/fat-cat-laser-eyes.gif" , "https://media.tenor.com/dBj14j2cu7gAAAAM/cat-cats.gif" , "https://media.tenor.com/uVRxyYWMOa8AAAAM/cat-black-cat.gif" , "https://media.tenor.com/2v1aDCelTJgAAAAM/cat-cats.gif" , "https://media.tenor.com/RgeZkYuEGiEAAAAM/gatoilse-cat-love.gif"],
    "dog": ["https://media.tenor.com/Nfct9RreQfUAAAAS/dog-meme.gif" , "https://media.tenor.com/bH4DmYV8V7QAAAAM/lauguningdog-dog.gif" , "https://media.tenor.com/twOxYKWAI5IAAAAM/dog.gif" , "https://media.tenor.com/3nB5e66NmtIAAAAM/dog-dog-tail-wagging.gif" , "https://media.tenor.com/JiRMdcRMYgoAAAAM/bellebows-happy-dog.gif" , "https://media.tenor.com/3U5KP3G7EVkAAAAM/hyejinsgenre-dog-meme.gif" , "https://media.tenor.com/bGOhVBvg9_kAAAAM/talking-dog-meme.gif" , "https://media.tenor.com/JIgNM-eR2pYAAAAM/dog.gif" , "https://media.tenor.com/lBpPIVojebAAAAAM/puppytalesphotos-puppytales.gif" , "https://media.tenor.com/Iv-vsEnjbGwAAAAM/dog.gif" , "https://media.tenor.com/YYNQWHTJZ5UAAAAM/look-at-this-dog-immediately-dog-meme.gif" , "https://media.tenor.com/OaibUW5AJQ8AAAAM/golden-retriever-dog.gif"],
    
    
    "crime-win": ["Снимая колпачки покрышек вы заработали " , "Вы украли сумку у девушки и заработали " , "Ограбив магазин вы заработали " , "Перевезя наркоту вы заработали "],
    "crime-lose": ["Вы перевозили наркоту, но вас решила остановить полиция, сумма проигыша " , "Вы ограбили магазин, но за вами погналась полиция, сумма проигрыша "],
}